<a href="https://colab.research.google.com/github/dachib04/CyberSecurity_LR_Model/blob/main/CyberSecurity_LR_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow
!pip install keras


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install numpy
!pip install scikit-learn
!pip install scipy


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install panda

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for panda: filename=panda-0.3.1-py3-none-any.whl size=7238 sha256=3a9a448592a6ed6a68835cfe2be7f0e701ec58a6c84d7a1c6f8c9242b5c633bb
  Stored in directory: /root/.cache/pip/wheels/0e/8b/c3/ff9cbde1fffd8071cff8367a86f0350a1ce30a8d31b6a432e9
Successfully built panda


In [ ]:
from google.colab import drive


In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd


df = pd.read_csv('/content/drive/MyDrive/folder/KDDTest.csv', header=None)
print('Read {} rows.'.format(len(df)))

df.dropna(inplace = True, axis = 1)

df.columns = [
    'duration',
    'protocol_type',
    'service',
    'flag',
    'src_bytes',
    'dst_bytes',
    'land',
    'wrong_fragment',
    'urgent',
    'hot',
    'num_failed_logins',
    'logged_in',
    'num_compromised',
    'root_shell',
    'su_attempted',
    'num_root',
    'num_file_creations',
    'num_shells',
    'num_access_file',
    'num_outbound_cmds',
    'is_host_login',
    'is_guest_login',
    'count',
    'srv_count',
    'serror_rate',
    'srv_serror_rate',
    'rerror_Rate',
    'srv_rerror_rate',
    'same_srv_rate',
    'diff_srv_rate',
    'srv_diff_host_rate',
    'dst_host_count',
    'dst_host_srv_count',
    'dst_host_same_srv_rate',
    'dst_host_diff_srv_rate',
    'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate',
    'dst_host_serror_rate',
    'dst_host_srv_serror_rate',
    'dst_host_rerror_rate',
    'dst_host_srv_rerror_rate',
    'outcome',
    'last_flag'
]

df[0:5]

Read 22544 rows.


duration protocol_type   service  flag  src_bytes  dst_bytes  land  \
0         0           tcp   private   REJ          0          0     0   
1         0           tcp   private   REJ          0          0     0   
2         2           tcp  ftp_data    SF      12983          0     0   
3         0          icmp     eco_i    SF         20          0     0   
4         1           tcp    telnet  RSTO          0         15     0   

   wrong_fragment  urgent  hot  ...  dst_host_same_srv_rate  \
0               0       0    0  ...                    0.04   
1               0       0    0  ...                    0.00   
2               0       0    0  ...                    0.61   
3               0       0    0  ...                    1.00   
4               0       0    0  ...                    0.31   

   dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
0                    0.06                         0.00   
1                    0.06                         0.00   
2                    0.04                         0.61   
3                    0.00                         1.00   
4                    0.17                         0.03   

   dst_host_srv_diff_host_rate  dst_host_serror_rate  \
0                         0.00                   0.0   
1                         0.00                   0.0   
2                         0.02                   0.0   
3                         0.28                   0.0   
4                         0.02                   0.0   

   dst_host_srv_serror_rate  dst_host_rerror_rate  dst_host_srv_rerror_rate  \
0                       0.0                  1.00                      1.00   
1                       0.0                  1.00                      1.00   
2                       0.0                  0.00                      0.00   
3                       0.0                  0.00                      0.00   
4                       0.0                  0.83                      0.71   

   outcome  last_flag  
0  neptune         21  
1  neptune         21  
2   normal         21  
3    saint         15  
4    mscan         11  

[5 rows x 43 columns]

In [ ]:
ENCODING = 'utf-8'

def expand_categories(values):
    result = []
    s = values.value_counts()
    t = float(len(values))
    for i in s.index:
        result.append("{}:{}%".format(i,round(100*(s[i]/t),2)))
    return '[{}]'.format(",".join(result))

def analyze(filename):
    print()
    print('Analyzing: {}'.format(filename))
    df = pd.read_csv(filename, encoding=ENCODING)
    cols = df.columns.values
    total = float(len(df))

    print('{} rows'.format(int(total)))
    for col in cols:
      uniques = df[col].unique()
      unique_count = len(uniques)
      if unique_count > 100:
          print('** {}:{} ({}%)'.format(col,unique_count,int(((unique_count)/total)*100)))
      else:
          print('** {}:{}'.format(col,expand_categories(df[col])))
          expand_categories(df[col])

In [ ]:
import os
import numpy as np
from sklearn import metrics
from scipy.stats import zscore

analyze('/content/drive/MyDrive/folder/KDDTest.csv')


Analyzing: /content/drive/MyDrive/folder/KDDTest.csv
22543 rows
** 0:624 (2%)
** tcp:[tcp:83.75%,udp:11.63%,icmp:4.63%]
** private:[http:34.84%,private:21.17%,telnet:7.21%,pop_3:4.52%,smtp:4.14%,domain_u:3.97%,ftp_data:3.78%,other:3.72%,ecr_i:3.34%,ftp:3.07%,imap4:1.36%,eco_i:1.16%,sunrpc:0.71%,finger:0.6%,auth:0.3%,domain:0.23%,uucp:0.22%,iso_tsap:0.21%,bgp:0.2%,uucp_path:0.2%,Z39_50:0.2%,vmnet:0.19%,nnsp:0.19%,ctf:0.18%,link:0.18%,whois:0.18%,courier:0.18%,name:0.16%,echo:0.16%,http_443:0.16%,time:0.16%,netbios_ns:0.16%,csnet_ns:0.15%,gopher:0.15%,efs:0.15%,mtp:0.14%,systat:0.14%,login:0.13%,daytime:0.12%,supdup:0.12%,exec:0.12%,netstat:0.12%,discard:0.12%,ssh:0.12%,netbios_dgm:0.11%,kshell:0.11%,urp_i:0.1%,hostnames:0.1%,klogin:0.09%,nntp:0.09%,ldap:0.08%,sql_net:0.08%,shell:0.07%,pm_dump:0.07%,netbios_ssn:0.07%,X11:0.07%,remote_job:0.06%,pop_2:0.06%,IRC:0.06%,printer:0.05%,ntp_u:0.04%,rje:0.04%,tim_i:0.03%,tftp_u:0.0%]
** REJ:[SF:65.99%,REJ:17.07%,S0:8.93%,RSTO:3.43%,RSTR:2.97%,S3

In [ ]:
def encode_numeric_zscore(df, name, mean=None, sd=None):
    if mean is None:
        mean = df[name].mean()

    if sd is None:
        sd = df[name].std()

    df[name] = (df[name] - mean) / sd

def encode_test_dummy(df, name):
    dummies = pd.get_dummies(df[name])
    for i in dummies.columns:
      dummy_name = "{}_{}".format(name, i)
      # dummy_name = f'{name}-{i}'
      df[dummy_name] = dummies[i]
    df.drop(name, axis=1, inplace=True)


In [ ]:


# Normalize numeric features
encode_numeric_zscore(df, 'duration')
encode_numeric_zscore(df, 'src_bytes')
encode_numeric_zscore(df, 'dst_bytes')
encode_numeric_zscore(df, 'wrong_fragment')
encode_numeric_zscore(df, 'urgent')
encode_numeric_zscore(df, 'hot')
encode_numeric_zscore(df, 'num_failed_logins')
encode_numeric_zscore(df, 'num_compromised')
encode_numeric_zscore(df, 'root_shell')
encode_numeric_zscore(df, 'su_attempted')
encode_numeric_zscore(df, 'num_root')
encode_numeric_zscore(df, 'num_file_creations')
encode_numeric_zscore(df, 'num_shells')
encode_numeric_zscore(df, 'num_access_file')
encode_numeric_zscore(df, 'count')
encode_numeric_zscore(df, 'srv_count')
encode_numeric_zscore(df, 'serror_rate')
encode_numeric_zscore(df, 'srv_serror_rate')
encode_numeric_zscore(df, 'rerror_Rate')
encode_numeric_zscore(df, 'srv_rerror_rate')
encode_numeric_zscore(df, 'same_srv_rate')
encode_numeric_zscore(df, 'diff_srv_rate')
encode_numeric_zscore(df, 'srv_diff_host_rate')
encode_numeric_zscore(df, 'dst_host_count')
encode_numeric_zscore(df, 'dst_host_srv_count')
encode_numeric_zscore(df, 'dst_host_same_srv_rate')
encode_numeric_zscore(df, 'dst_host_diff_srv_rate')
encode_numeric_zscore(df, 'dst_host_same_src_port_rate')
encode_numeric_zscore(df, 'dst_host_srv_diff_host_rate')
encode_numeric_zscore(df, 'dst_host_serror_rate')
encode_numeric_zscore(df, 'dst_host_srv_serror_rate')
encode_numeric_zscore(df, 'dst_host_rerror_rate')
encode_numeric_zscore(df, 'dst_host_srv_rerror_rate')

# Encode categorical features
encode_test_dummy(df, 'protocol_type')
encode_test_dummy(df, 'service')
encode_test_dummy(df, 'flag')
encode_test_dummy(df, 'land')
encode_test_dummy(df, 'logged_in')
encode_test_dummy(df, 'is_guest_login')

df.dropna(inplace=True, axis=1)
df[0:5]


x_columns = df.columns.drop('outcome')
x = df[x_columns].values
dummies = pd.get_dummies(df['outcome'])
outcomes = dummies.columns
num_classes = len(outcomes)
y = dummies.values



<ipython-input-12-70072c4234f8>:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[dummy_name] = dummies[i]
<ipython-input-12-70072c4234f8>:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[dummy_name] = dummies[i]
<ipython-input-12-70072c4234f8>:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
 

In [ ]:
x_columns = df.columns.drop('outcome')
x = df[x_columns].values
dummies = pd.get_dummies(df['outcome'])
outcomes = dummies.columns
num_classes = len(outcomes)
y = dummies.values


In [ ]:
df.groupby('outcome')['outcome'].count()

outcome
apache2             737
back                359
buffer_overflow      20
ftp_write             3
guess_passwd       1231
httptunnel          133
imap                  1
ipsweep             141
land                  7
loadmodule            2
mailbomb            293
mscan               996
multihop             18
named                17
neptune            4657
nmap                 73
normal             9711
perl                  2
phf                   2
pod                  41
portsweep           157
processtable        685
ps                   15
rootkit              13
saint               319
satan               735
sendmail             14
smurf               665
snmpgetattack       178
snmpguess           331
sqlattack             2
teardrop             12
udpstorm              2
warezmaster         944
worm                  2
xlock                 9
xsnoop                4
xterm                13
Name: outcome, dtype: int64

In [ ]:



import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# Load the data
df = pd.read_csv('/content/drive/MyDrive/folder/KDDTest.csv', header=None)

# Assign column names to the dataframe
col_names = ['duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment',
             'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted',
             'num_root', 'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds',
             'is_hot_login', 'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate',
             'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate',
             'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
             'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
             'dst_host_srv_serror_rate', 'dst_host_rerror_rate', 'dst_host_srv_rerror_rate', 'outcome', 'last_flag']

df.columns = col_names

# Drop columns that have constant values or unique for each record
df.drop(['num_outbound_cmds', 'is_hot_login', 'is_guest_login'], axis=1, inplace=True)

# Filter for non-normal outcomes
attacks = df[df['outcome'] != 'normal']
attack_types = attacks['outcome'].unique()

print(f"Types of cyber attacks in the dataset: {', '.join(attack_types)}")

# One-hot encode categorical variables
df = pd.get_dummies(df, columns=['protocol_type', 'service', 'flag'])

# Split the data into train and test sets
X = df.drop('outcome', axis=1)
y = df['outcome']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Scale the numerical variables
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train a logistic regression model
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)

# Make predictions on the test set and calculate accuracy
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Print the confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)
print(f"Confusion matrix:\n{confusion_mat}")



Types of cyber attacks in the dataset: neptune, saint, mscan, guess_passwd, smurf, apache2, satan, buffer_overflow, back, warezmaster, snmpgetattack, processtable, pod, httptunnel, nmap, ps, snmpguess, ipsweep, mailbomb, portsweep, multihop, named, sendmail, loadmodule, xterm, worm, teardrop, rootkit, xlock, perl, land, xsnoop, sqlattack, ftp_write, imap, udpstorm, phf
Accuracy: 0.9756061502069782
Confusion matrix:
[[211   0   0 ...   0   0   0]
 [  0  88   0 ...   0   0   0]
 [  0   0   4 ...   0   0   0]
 ...
 [  0   0   0 ...   2   0   0]
 [  0   0   0 ...   1   0   0]
 [  0   0   1 ...   0   0   1]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
